### ISSUE TITLE
pooledTaskBroker preload options?

### ISSUE THREAD

**Issue by smalbs** [deployr/js-rbroker-framework#2]
I'm trying to preload an .RData file with my pooledBroker and having some trouble.

The [api on the website](http://deployr.revolutionanalytics.com/documents/dev/rbroker-jsdoc/#pbrokerfactory) lists the ability to include preload options with the broker config, but the documentation is a little odd and doesn't describe what the object keys are.

After digging into the broker codebase I've found the following config options:
- preloadfilename
- preloaddirectory
- preloadfileauthor
- preloadfileversion

However it looks like these are only applied in the 'refresh' method and not during initialization. 

Any advice?

**Comment by swells** [comment]
Hello,

However it looks like these are only applied in the 'refresh' method and

> not during initialization.

I don't think that is the case, however I will need to check it. If you
look at this test
https://github.com/deployr/js-rbroker-framework/blob/master/test/specs/pooled-task-broker-test.js#L191
and
trace it back slightly to
what is actually being included
https://github.com/deployr/js-rbroker-framework/blob/master/test/fixtures/common.js#L20
under
the `pool` object literal,  you will see a good working example on how to
use it:

```
        brokerConfig = {
            host: fixtures.endpoint,
            credentials: fixtures.credentials,
            maxConcurrentTaskLimit: MAX_CONCURRENCY,
            releaseGridResources: true,
           * pool: fixtures.good()
<https://github.com/deployr/js-rbroker-framework/blob/master/test/fixtures/common.js#L20>*
        };
```

A  good rule of thumb regarding the JavaScript libraries/rbroker is that
the parameter names always map exactly
to the API Reference Guide
http://deployr.revolutionanalytics.com/documents/dev/api-doc/ documentation
for an API. So more specially to this `job pool` context:

```
brokerConfig = {
    pool: {
       //   Under the hood this call does a `/r/job/submit` and Should map
all parameter name/value defined here
<http://deployr.revolutionanalytics.com/documents/dev/api-doc/guide/workingjobs.html#jobsubmit>
    }
};
```

So this mean all the: Parameters, Pre-Execution Parameters, On-Execution
Parameters, Post-Execution Parameters will be accepted.

I will try and make the docs more descriptive, I can see the confusion. Let
us know how it turns out.
- Sean
